plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

version = project.mod_version
group = project.mod_group

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

neoForge {
    version = project.neoforge_version

    runs {
        server {
            server()
        }
        client {
            client()
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
            'Implementation-Title'  : project.mod_name,
            'Implementation-Version': project.mod_version,
        ])
    }
}
