# Mod properties
mod_id=ganjagate
mod_name=GanjaGate
mod_version=1.0.0
mod_group=ru.ganj4craft.gate
mod_authors=GanjaMonsta
mod_description=Server-side anti-cheat mod for GanjaCraft. Verifies client mod list during connection.

# NeoForge / Minecraft
minecraft_version=1.21.1
neoforge_version=21.1.247

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
